### ISSUE TITLE
Getting following error Payment_method_missing

### ISSUE THREAD

**Issue by chiragmewada** [anilahir/omnipay-payeezy#1]
[{"code":"payment_method_missing","description":"The payment method is missing"}]

Can you please help me what I am doing wrong

**Comment by anilahir** [comment]
Hi, @chiragmewada 
You need to pass 'payment_profile' as payment_method.

![selection_067](https://user-images.githubusercontent.com/10591317/46931963-22e04000-d06b-11e8-9fa8-75602dd365f7.png)

**Comment by chiragmewada** [comment]
Thanks for the reply.
I am still stuck and unable to set payment_method. I tried to specify it in the multiple files but it does not work.

Help will be really appreciated.

**Comment by anilahir** [comment]
Following link will help you to set it up
https://github.com/anilahir/laravel-omnipay/blob/master/README.md
